### ISSUE TITLE
Upstream version 1.1.9 is available

### ISSUE THREAD

**Issue by zbynekwinkler** [conda-forge/autograd-feedstock#2]
I am not sure what the best source for new versions is, but it might be a good idea to be in sync with pypi:

https://pypi.python.org/packages/54/9c/d5d6abd14c4c5dee1489b530da238004fed4ea76cf48a196ba8fe40baa17/autograd-1.1.9.tar.gz#md5=0a23c7d244fb4fb0a44a3c6711381ad0

**Comment by richardotis** [comment]
Thanks for the note. This should be fixed when #3 is merged.

**Comment by richardotis** [comment]
1.19 is now deployed on conda forge.
